// This work is licensed under a Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0) https://creativecommons.org/licenses/by-nc-sa/4.0/
// © LuxAlgo

//@version=5
strategy("SwingFairValueGap Combined [LuxAlgo]", "SwingFairValueGap Combined Data", overlay = true, max_lines_count = 500, max_boxes_count = 500)



//Swing Failure Pattern [LuxAlgo] Section

//-----------------------------------------------------------------------------}
//---------------------------------------------------------------------------------------------------------------------}
//Settings
//---------------------------------------------------------------------------------------------------------------------{
sp         =                              '            '
len        = input.int      (   5       ,    'Swings'      , minval=  1                               )
bull       = input.bool     ( true      ,  'Bullish SFP'                                              )
bear       = input.bool     ( true      ,  'Bearish SFP'                                              )

iVal       = input.string   ('None', 'Validation'+sp+ '   ', group='Volume Validation'
 , options =          ['Volume outside swing < Threshold'  ,'Volume outside swing > Threshold','None'])
percent    = input.float    (25, 'Volume Threshold %'      , inline='valy', group='Volume Validation'
 , tooltip =                    '% of Total Volume'        , minval=  0   , maxval=100                )
autoSwing       = input.bool     (true,     ''                  , inline='auto', group='Volume Validation' )
mlt        = input.int      (50  ,  '      Auto' + sp      , inline='auto', group='Volume Validation' )
res        = input.timeframe('1' , sp +'   LTF'  + sp +'  ', inline='ltf' , group='Volume Validation' )
prem       = input.bool     (false   ,'    Premium'                       , group='Volume Validation'
 , tooltip =                        'Premium Plan or higher'                                          )
showDashSwing   = input.bool     (true    , 'Show Dashboard'                   , group=    'Dashboard'     )
dashLocSwing    = input.string   (           'Top Right'        , 'Location'  
 , options =                ['Top Right', 'Bottom Right', 'Bottom Left']  , group=    'Dashboard'     )
textSizeSwing   = input.string   (             'Normal'         ,   'Size'      
 , options =                     ['Tiny', 'Small', 'Normal']              , group=    'Dashboard'     )
dSwingLine = input.bool     (true    ,  'Swing Lines'                     , group=      'Style'       )
dOpposLine = input.bool     (true    ,  'Confirmation Lines'              , group=      'Style'       )
dSFP_Line  = input.bool     (true    ,  'Swing Failure Wick'              , group=      'Style'       )
dSFP_Label = input.bool     (true    ,  'Swing Failure Label'             , group=      'Style'       )
colBl      = input.color    (#089981  , 'Lines / Labels' , inline='lin' , group=      'Style'       )
colBr      = input.color    (#f23645  ,   ''             , inline='lin' , group=      'Style'      
 , tooltip =                         'Bullish/Bearish'                                                )
colBl2     = input.color    (#08998180, 'SFP Wicks      ', inline='wic' , group=      'Style'       )
colBr2     = input.color    (#f2364580,   ''             , inline='wic' , group=      'Style'      
 , tooltip =                'Wick outside Swing, Bullish/Bearish'                                     )

//-----------------------------------------------------------------------------}      
//UDT
//-----------------------------------------------------------------------------{
type piv
    float swing_prc // price
    int   swing_bix // bar_index
    float oppos_prc // price
    int   oppos_bix // bar_index
    bool  active    
    bool  confirmed 
    line  swing_line 
    line  oppos_line 
    line  wicky_line
    label wicky_label

type swing 
    int   bix 
    float prc 

//-----------------------------------------------------------------------------}      
//Variables
//-----------------------------------------------------------------------------{
nSwing   = bar_index 
INV = color(na)
FGc = chart.fg_color

table_positionSwing = dashLocSwing == 'Bottom Left' ? position.bottom_left 
  : dashLocSwing == 'Top Right' ? position.top_right 
  : position.bottom_right

table_sizeSwing = textSizeSwing == 'Tiny' ? size.tiny 
  : textSizeSwing == 'Small' ? size.small 
  : size.normal

var tbSwing = table.new(table_positionSwing, 2, 3
  , bgcolor      = #1e222d
  , border_color = #373a46
  , border_width = 1
  , frame_color  = #373a46
  , frame_width  = 1)

var swing swingH = swing.new() 
var swing swingL = swing.new() 
var piv pivH     = piv.new()
var piv pivL     = piv.new()

validate = iVal != 'None' 
valHigher= iVal == 'Volume outside swing > Threshold'
valLower = iVal == 'Volume outside swing < Threshold'

//---------------------------------------------------------------------------------------------------------------------}
//Method
//---------------------------------------------------------------------------------------------------------------------{
method n(float piv) => bool out = not na(piv)

//---------------------------------------------------------------------------------------------------------------------}
//Execution
//---------------------------------------------------------------------------------------------------------------------{
tfS  = timeframe.in_seconds(      res       )
tfC  = timeframe.in_seconds(timeframe.period)
rs   = autoSwing ? tfC / mlt : tfS 
if not validate
    res := timeframe.period 
else
    rs  := prem ? rs : math.max(60, rs)
    res := timeframe.from_seconds(math.min(tfC, rs))

ph = ta.pivothigh(len, 1)
pl = ta.pivotlow (len, 1)

[ltf_close, ltf_volume] = request.security_lower_tf(syminfo.tickerid, res, [close, volume])

ltf_size = ltf_close.size()

if validate 
    if ltf_size > 0 and ltf_size[1] == 0 
        line.new(nSwing, close, nSwing, close + syminfo.mintick, color=color.silver, style=line.style_dotted, extend=extend.both)

//---------------------------------------------------------------------------------------------------------------------}
//Bearish Pattern
//---------------------------------------------------------------------------------------------------------------------{
if bear

    if ph.n() 
        swingH.bix := nSwing-1 
        swingH.prc := ph 

    sw = swingH.prc
    bx = swingH.bix
    if high > sw 
     and open < sw
     and close < sw
        valid = true
        if validate 
            if ltf_close.size() > 0 
                outsideVolume = 0.
                totalVolume = ltf_volume.sum() 
                for j = 0 to ltf_close.size() -1 
                    if ltf_close.get(j) > sw
                        outsideVolume += ltf_volume.get(j)
                if (valHigher ? 100 / totalVolume * outsideVolume < percent 
                              : 100 / totalVolume * outsideVolume > percent 
                   )
                    valid := false

                //if valid 
                //    label.new(n, high, text=str.format("Total Volume: {0}\nWick Volume: {1}", totalVolume, outsideVolume))

        if valid 

            opposL = sw 
            opposB = nSwing

            for i = 1 to nSwing - bx -1
                if low [i] < opposL 
                    opposL := low [i]
                    opposB := nSwing  - i

            if not pivH.confirmed
                pivH.swing_line .delete()
                pivH.oppos_line .delete()
                pivH.wicky_line .delete()                
                pivH.wicky_label.delete()

            pivH := piv.new(sw, bx, opposL, opposB, true, false)

            if dSwingLine 
                pivH.swing_line  := line.new (bx    , sw    , nSwing, sw    , color=colBr)
            if dOpposLine 
                pivH.oppos_line  := line.new (opposB, opposL, nSwing, opposL, color=colBr, style=line.style_dotted)
            if dSFP_Line 
                pivH.wicky_line  := line.new (nSwing     , high  , nSwing, sw    , color=colBr2, width=3)
            if dSFP_Label  
                pivH.wicky_label := label.new(nSwing     , high
                 , style=label.style_label_down
                 , text='SFP', textcolor=colBr
                 , color=INV, size=size.normal
                 )

    if pivH.active and not pivH.confirmed 

        pivH.swing_line.set_x2(nSwing)
        pivH.oppos_line.set_x2(nSwing)

        if close < pivH.oppos_prc
            pivH.confirmed   := true
                
            if pivH.wicky_label.get_x() == nSwing  
                pivH.wicky_label.set_text('SFP\n▼')
            else 
                label.new(nSwing, high, style=label.style_label_down, text='▼', textcolor=colBr, color=INV, size=size.normal)

    if nSwing - pivH.swing_bix > 500 
     or close > pivH.swing_prc
        pivH.active := false 
        if not pivH.confirmed
            pivH.swing_line .delete() 
            pivH.oppos_line .delete() 
            pivH.wicky_line .delete() 
            pivH.wicky_label.delete() 

//---------------------------------------------------------------------------------------------------------------------}
//Bullish Pattern
//---------------------------------------------------------------------------------------------------------------------{
if bull

    if pl.n() 
        swingL.bix := nSwing-1 
        swingL.prc := pl 

    sw = swingL.prc
    bx = swingL.bix
    if low  < sw 
     and open > sw
     and close > sw
        valid = true
        if validate 
            if ltf_close.size() > 0 
                outsideVolume = 0.
                totalVolume = ltf_volume.sum() 
                for j = 0 to ltf_close.size() -1 
                    if ltf_close.get(j) < sw
                        outsideVolume += ltf_volume.get(j)
                if (valHigher ? 100 / totalVolume * outsideVolume < percent 
                              : 100 / totalVolume * outsideVolume > percent 
                   )
                    valid := false
        if valid 

            opposH = sw 
            opposB = nSwing

            for i = 1 to nSwing - bx -1
                if high[i] > opposH 
                    opposH := high[i]
                    opposB := nSwing - i

            if not pivL.confirmed
                pivL.swing_line .delete()
                pivL.oppos_line .delete()
                pivL.wicky_line .delete()                
                pivL.wicky_label.delete()

            pivL := piv.new(sw, bx, opposH, opposB, true, false)

            if dSwingLine 
                pivL.swing_line  := line.new (bx    , sw    , nSwing, sw    , color=colBl )
            if dOpposLine 
                pivL.oppos_line  := line.new (opposB, opposH, nSwing, opposH, color=colBl , style=line.style_dotted)
            if dSFP_Line 
                pivL.wicky_line  := line.new (nSwing     , low   , nSwing, sw    , color=colBl2, width=3)
            if dSFP_Label  
                pivL.wicky_label := label.new(nSwing     , low  
                 , style=label.style_label_up
                 , text='SFP', textcolor=colBl
                 , color=INV, size=size.normal
                 )

    if pivL.active and not pivL.confirmed 

        pivL.swing_line.set_x2(nSwing)
        pivL.oppos_line.set_x2(nSwing)

        if close > pivL.oppos_prc
            pivL.confirmed   := true
                
            if pivL.wicky_label.get_x() == nSwing  
                pivL.wicky_label.set_text('▲\nSFP')
            else 
                label.new(nSwing, low, style=label.style_label_up, text='▲', textcolor=colBl, color=INV, size=size.normal)

    if nSwing - pivL.swing_bix > 500 
     or close < pivL.swing_prc
        pivL.active := false 
        if not pivL.confirmed
            pivL.swing_line .delete() 
            pivL.oppos_line .delete() 
            pivL.wicky_line .delete() 
            pivL.wicky_label.delete() 

//---------------------------------------------------------------------------------------------------------------------}
//Dashboard
//---------------------------------------------------------------------------------------------------------------------{
if barstate.islast and validate and showDashSwing
    tbSwing.cell(0, 0, str.format("LTF: {0}", res), text_color=color.white, text_size=table_sizeSwing)

//---------------------------------------------------------------------------------------------------------------------}


//Fair Value Gap Section
//------------------------------------------------------------------------------
//Settings
//-----------------------------------------------------------------------------{
thresholdPer = input.float(0, "Threshold %", minval = 0, maxval = 100, step = .1, inline = 'threshold')
auto = input(false, "Auto", inline = 'threshold')

showLast = input.int(0, 'Unmitigated Levels', minval = 0)
mitigationLevels = input.bool(false, 'Mitigation Levels')

tf = input.timeframe('', "Timeframe")

//Style
extend = input.int(20, 'Extend', minval = 0, inline = 'extend', group = 'Style')
dynamic = input(false, 'Dynamic', inline = 'extend', group = 'Style')

bullCss = input.color(color.new(#089981, 70), "Bullish FVG", group = 'Style')
bearCss = input.color(color.new(#f23645, 70), "Bearish FVG", group = 'Style')

//Dashboard
showDash  = input(false, 'Show Dashboard', group = 'Dashboard')
dashLoc  = input.string('Top Right', 'Location', options = ['Top Right', 'Bottom Right', 'Bottom Left'], group = 'Dashboard')
textSize = input.string('Small', 'Size'        , options = ['Tiny', 'Small', 'Normal']                 , group = 'Dashboard')

//-----------------------------------------------------------------------------}
//UDT's
//-----------------------------------------------------------------------------{
type fvg
    float max
    float min
    bool  isbull
    int   t = time

//-----------------------------------------------------------------------------}
//Methods/Functions
//-----------------------------------------------------------------------------{
n = bar_index

method tosolid(color id)=> color.rgb(color.r(id),color.g(id),color.b(id))

detect()=>
    var new_fvg = fvg.new(na, na, na, na)
    threshold = auto ? ta.cum((high - low) / low) / bar_index : thresholdPer / 100

    bull_fvg = low > high[2] and close[1] > high[2] and (low - high[2]) / high[2] > threshold
    bear_fvg = high < low[2] and close[1] < low[2] and (low[2] - high) / high > threshold
    
    if bull_fvg
        new_fvg := fvg.new(low, high[2], true)
    else if bear_fvg
        new_fvg := fvg.new(low[2], high, false)

    [bull_fvg, bear_fvg, new_fvg]

//-----------------------------------------------------------------------------}
//FVG's detection/display
//-----------------------------------------------------------------------------{
var float max_bull_fvg = na, var float min_bull_fvg = na, var bull_count = 0, var bull_mitigated = 0
var float max_bear_fvg = na, var float min_bear_fvg = na, var bear_count = 0, var bear_mitigated = 0
var t = 0

var fvg_records = array.new<fvg>(0)
var fvg_areas = array.new<box>(0)

[bull_fvg, bear_fvg, new_fvg] = request.security(syminfo.tickerid, tf, detect())

//Bull FVG's
if bull_fvg and new_fvg.t != t
    if dynamic
        max_bull_fvg := new_fvg.max
        min_bull_fvg := new_fvg.min
    
    //Populate FVG array
    if not dynamic
        fvg_areas.unshift(box.new(n-2, new_fvg.max, n+extend, new_fvg.min, na, bgcolor = bullCss))
    fvg_records.unshift(new_fvg)

    bull_count += 1
    t := new_fvg.t
else if dynamic
    max_bull_fvg := math.max(math.min(close, max_bull_fvg), min_bull_fvg)

//Bear FVG's
if bear_fvg and new_fvg.t != t
    if dynamic
        max_bear_fvg := new_fvg.max
        min_bear_fvg := new_fvg.min
    
    //Populate FVG array
    if not dynamic
        fvg_areas.unshift(box.new(n-2, new_fvg.max, n+extend, new_fvg.min, na, bgcolor = bearCss))
    fvg_records.unshift(new_fvg)

    bear_count += 1
    t := new_fvg.t
else if dynamic
    min_bear_fvg := math.min(math.max(close, min_bear_fvg), max_bear_fvg) 

//-----------------------------------------------------------------------------}
//Unmitigated/Mitigated lines
//-----------------------------------------------------------------------------{
//Test for mitigation
if fvg_records.size() > 0
    for i = fvg_records.size()-1 to 0
        get = fvg_records.get(i)

        if get.isbull
            if close < get.min
                //Display line if mitigated
                if mitigationLevels
                    line.new(get.t, get.min, time, get.min, xloc.bar_time, color = bullCss, style = line.style_dashed)

                //Delete box
                if not dynamic
                    area = fvg_areas.remove(i)
                    area.delete()

                fvg_records.remove(i)
                bull_mitigated += 1
        else if close > get.max
            //Display line if mitigated
            if mitigationLevels
                line.new(get.t, get.max, time, get.max, xloc.bar_time, color = bearCss, style = line.style_dashed)

            //Delete box
            if not dynamic
                area = fvg_areas.remove(i)
                area.delete()
            
            fvg_records.remove(i)
            bear_mitigated += 1

//Unmitigated lines
var unmitigated = array.new<line>(0)

//Remove umitigated lines 
if barstate.islast and showLast > 0 and fvg_records.size() > 0
    if unmitigated.size() > 0 
        for element in unmitigated
            element.delete()
        unmitigated.clear()

    for i = 0 to math.min(showLast-1, fvg_records.size()-1)
        get = fvg_records.get(i)

        unmitigated.push(line.new(get.t
          , get.isbull ? get.min : get.max 
          , time
          , get.isbull ? get.min : get.max
          , xloc.bar_time
          , color = get.isbull ? bullCss : bearCss))

//-----------------------------------------------------------------------------}
//Dashboard
//-----------------------------------------------------------------------------{
var table_position = dashLoc == 'Bottom Left' ? position.bottom_left 
  : dashLoc == 'Top Right' ? position.top_right 
  : position.bottom_right

var table_size = textSize == 'Tiny' ? size.tiny 
  : textSize == 'Small' ? size.small 
  : size.normal

var tb = table.new(table_position, 3, 3
  , bgcolor = #1e222d
  , border_color = #373a46
  , border_width = 1
  , frame_color = #373a46
  , frame_width = 1)

if showDash
    if barstate.isfirst
        tb.cell(1, 0, 'Bullish', text_color = bullCss.tosolid(), text_size = table_size)
        tb.cell(2, 0, 'Bearish', text_color = bearCss.tosolid(), text_size = table_size)
    
        tb.cell(0, 1, 'Count', text_size = table_size, text_color = color.white)
        tb.cell(0, 2, 'Mitigated', text_size = table_size, text_color = color.white)
    
    if barstate.islast
        tb.cell(1, 1, str.tostring(bull_count), text_color = bullCss.tosolid(), text_size = table_size)
        tb.cell(2, 1, str.tostring(bear_count), text_color = bearCss.tosolid(), text_size = table_size)
        
        tb.cell(1, 2, str.tostring(bull_mitigated / bull_count * 100, format.percent), text_color = bullCss.tosolid(), text_size = table_size)
        tb.cell(2, 2, str.tostring(bear_mitigated / bear_count * 100, format.percent), text_color = bearCss.tosolid(), text_size = table_size)

//-----------------------------------------------------------------------------}
//Plots
//-----------------------------------------------------------------------------{
//Dynamic Bull FVG
max_bull_plot = plot(max_bull_fvg, color = na)
min_bull_plot = plot(min_bull_fvg, color = na)
fill(max_bull_plot, min_bull_plot, color = bullCss)


//Dynamic Bear FVG
max_bear_plot = plot(max_bear_fvg, color = na)
min_bear_plot = plot(min_bear_fvg, color = na)
fill(max_bear_plot, min_bear_plot, color = bearCss)

//-----------------------------------------------------------------------------}
//Alerts
//-----------------------------------------------------------------------------{
alertcondition(bull_count > bull_count[1], 'Bullish FVG', 'Bullish FVG detected')
alertcondition(bear_count > bear_count[1], 'Bearish FVG', 'Bearish FVG detected')

alertcondition(bull_mitigated > bull_mitigated[1], 'Bullish FVG Mitigation', 'Bullish FVG mitigated')
alertcondition(bear_mitigated > bear_mitigated[1], 'Bearish FVG Mitigation', 'Bearish FVG mitigated')
